# Generated by Django 4.1.7 on 2023-03-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Dni')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('descripcionProblema', models.CharField(max_length=300, unique=True, verbose_name=' Descripcion del Problema')),
                ('clasificacion', models.CharField(max_length=300, unique=True, verbose_name='clasificacion')),
                ('normaIncumplida', models.CharField(max_length=300, unique=True, verbose_name=' normaIncumplida')),
                ('tipoAccion', models.CharField(max_length=300, unique=True, verbose_name='tipoAccion')),
                ('fuentePlan', models.CharField(max_length=300, unique=True, verbose_name='fuentePlan')),
                ('entidad', models.CharField(max_length=300, unique=True, verbose_name='entidad')),
                ('proceso', models.CharField(max_length=300, unique=True, verbose_name='proceso')),
                ('tratamientoInmediato', models.CharField(max_length=300, unique=True, verbose_name='tratamientoInmediato')),
                ('evidencia', models.CharField(max_length=300, unique=True, verbose_name=' evidencia')),
                ('analisisCausa', models.CharField(max_length=300, unique=True, verbose_name='  analisisCausa')),
                ('causaRaiz', models.CharField(max_length=300, unique=True, verbose_name=' causaRaiz')),
                ('estado', models.CharField(max_length=300, unique=True, verbose_name='estado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagen/%Y/%m/%d')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='imagen/%Y/%m/%d')),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.category')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['id'],
            },
        ),
    ]
